edition = "2024"
unstable_features = true
style_edition = "2024"

format_macro_matchers = true
format_macro_bodies = true
format_code_in_doc_comments = true

max_width = 120
fn_single_line = false
empty_item_single_line = true
struct_lit_single_line = false
match_block_trailing_comma = true
overflow_delimited_expr = true
use_small_heuristics = "Max"
condense_wildcard_suffixes = true
use_field_init_shorthand = true

comment_width = 80
wrap_comments = true

reorder_modules = true
reorder_impl_items = true
reorder_imports = true

imports_granularity = "Crate"
group_imports = "StdExternalCrate"
